code/task_hero/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "authentication"

urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path('log-in/', LoginView.as_view(template_name="authentication/log-in.html"), name="login"),
    path('log-out/', LogoutView.as_view(), name="logout"),
]

code/task_hero/config/urls.py

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_app.urls")),
    path("auth/", include("authentication.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/task_hero/task_app/urls.py
from django.urls import path
from . import views


app_name = "task_app"

urlpatterns = [
    path("home/", views.home, name="home"),
    path('update/<int:task_id>/', views.update_task, name='update_task'),
    path('confirm-delete/<int:task_id>/', views.confirm_delete_task, name='confirm_delete_task'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add/', views.add_task, name='add_task'),
    path('task_detail/<int:task_id>/', views.task_detail, name='task_detail'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
   
]

code/task_hero/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://kit.fontawesome.com/2b5e34dc4a.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
<div class="login-text">
    {% if messages %}
        <ul>
            {% for message in messages %}
            <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %} 
</div>

        
<header class="auth-container">
    {% if request.user.is_authenticated %}
        <form action="{% url 'authentication:logout' %}" method="POST">
            {% csrf_token %}
            <button type= "submit" class="btn">Log out</button>
        </form>
        <h3>
            Welcome, {{ request.user }}
        </h3>
    {% else %}
        <a href="{% url 'authentication:login' %}">Log in</a>
    {% endif %}

    
</header>
<body>

       
 {% include "./header.html" %} 

{% block body %}

{% endblock body %}



{% block scripts %}
<script src="{% static 'js/to-do.js' %}"></script>
{% endblock scripts %}


</body>
</html>

code/task_hero/templates/partials/header.html
{% load static %}
<header class ="top_logo"><a href="{% url 'task_app:home' %}">ChoreChampion</a></header>


    <div class="greeting" id="timeGreeting">
        <h2>{{ greeting }} </h2>
        {% if time_of_day == 'morning' %}
            <img src="{% static 'images/sunset.jpg' %}" alt="Morning Image">
        {% elif time_of_day == 'day' %}
            <img src="{% static 'images/sun2.jpg' %}" alt="Sun Image">
        {% elif time_of_day == 'night' %}
            <img src="{% static 'images/half_moon.jpg' %}" alt="Moon Image">
        {% elif time_of_day == 'Late night' %}
            <img src="{% static 'images/moon2.jpg' %}" alt="Moon ">
        {% endif %}
    </div>
